// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/user.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Employee struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateOfBirth   string                 `protobuf:"bytes,4,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"` // yyyy-mm-dd
	Gender        string                 `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,7,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Address       string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	Username      string                 `protobuf:"bytes,9,opt,name=username,proto3" json:"username,omitempty"`
	Position      string                 `protobuf:"bytes,10,opt,name=position,proto3" json:"position,omitempty"`
	Department    string                 `protobuf:"bytes,11,opt,name=department,proto3" json:"department,omitempty"`
	Active        bool                   `protobuf:"varint,12,opt,name=active,proto3" json:"active,omitempty"`
	Permissions   []string               `protobuf:"bytes,13,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Employee) Reset() {
	*x = Employee{}
	mi := &file_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Employee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Employee) ProtoMessage() {}

func (x *Employee) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Employee.ProtoReflect.Descriptor instead.
func (*Employee) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *Employee) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Employee) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Employee) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Employee) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *Employee) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *Employee) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Employee) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Employee) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Employee) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Employee) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *Employee) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *Employee) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Employee) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type CreateEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateOfBirth   string                 `protobuf:"bytes,3,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Gender        string                 `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Address       string                 `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	Username      string                 `protobuf:"bytes,8,opt,name=username,proto3" json:"username,omitempty"`
	Position      string                 `protobuf:"bytes,9,opt,name=position,proto3" json:"position,omitempty"`
	Department    string                 `protobuf:"bytes,10,opt,name=department,proto3" json:"department,omitempty"`
	Active        bool                   `protobuf:"varint,11,opt,name=active,proto3" json:"active,omitempty"`
	Permissions   []string               `protobuf:"bytes,12,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmployeeRequest) Reset() {
	*x = CreateEmployeeRequest{}
	mi := &file_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmployeeRequest) ProtoMessage() {}

func (x *CreateEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmployeeRequest.ProtoReflect.Descriptor instead.
func (*CreateEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEmployeeRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateEmployeeRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateEmployeeRequest) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *CreateEmployeeRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *CreateEmployeeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateEmployeeRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CreateEmployeeRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateEmployeeRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateEmployeeRequest) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *CreateEmployeeRequest) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *CreateEmployeeRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *CreateEmployeeRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type GetEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    uint64                 `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeRequest) Reset() {
	*x = GetEmployeeRequest{}
	mi := &file_proto_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeRequest) ProtoMessage() {}

func (x *GetEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeRequest.ProtoReflect.Descriptor instead.
func (*GetEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetEmployeeRequest) GetEmployeeId() uint64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

type UpdateEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    uint64                 `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateOfBirth   string                 `protobuf:"bytes,4,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Gender        string                 `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,7,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Address       string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	Position      string                 `protobuf:"bytes,9,opt,name=position,proto3" json:"position,omitempty"`
	Department    string                 `protobuf:"bytes,10,opt,name=department,proto3" json:"department,omitempty"`
	Active        bool                   `protobuf:"varint,11,opt,name=active,proto3" json:"active,omitempty"`
	Permissions   []string               `protobuf:"bytes,12,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmployeeRequest) Reset() {
	*x = UpdateEmployeeRequest{}
	mi := &file_proto_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmployeeRequest) ProtoMessage() {}

func (x *UpdateEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmployeeRequest.ProtoReflect.Descriptor instead.
func (*UpdateEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateEmployeeRequest) GetEmployeeId() uint64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *UpdateEmployeeRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *UpdateEmployeeRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type DeleteEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    uint64                 `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEmployeeRequest) Reset() {
	*x = DeleteEmployeeRequest{}
	mi := &file_proto_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEmployeeRequest) ProtoMessage() {}

func (x *DeleteEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEmployeeRequest.ProtoReflect.Descriptor instead.
func (*DeleteEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteEmployeeRequest) GetEmployeeId() uint64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

type ListEmployeesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Position      string                 `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEmployeesRequest) Reset() {
	*x = ListEmployeesRequest{}
	mi := &file_proto_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEmployeesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEmployeesRequest) ProtoMessage() {}

func (x *ListEmployeesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEmployeesRequest.ProtoReflect.Descriptor instead.
func (*ListEmployeesRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{5}
}

func (x *ListEmployeesRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ListEmployeesRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *ListEmployeesRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *ListEmployeesRequest) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

type ListEmployeesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employees     []*Employee            `protobuf:"bytes,1,rep,name=employees,proto3" json:"employees,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEmployeesResponse) Reset() {
	*x = ListEmployeesResponse{}
	mi := &file_proto_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEmployeesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEmployeesResponse) ProtoMessage() {}

func (x *ListEmployeesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEmployeesResponse.ProtoReflect.Descriptor instead.
func (*ListEmployeesResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{6}
}

func (x *ListEmployeesResponse) GetEmployees() []*Employee {
	if x != nil {
		return x.Employees
	}
	return nil
}

type Client struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName         string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName          string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateOfBirth       int64                  `protobuf:"varint,4,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"` // Unix timestamp
	Gender            string                 `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Email             string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber       string                 `protobuf:"bytes,7,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Address           string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	ConnectedAccounts []string               `protobuf:"bytes,9,rep,name=connected_accounts,json=connectedAccounts,proto3" json:"connected_accounts,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Client) Reset() {
	*x = Client{}
	mi := &file_proto_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{7}
}

func (x *Client) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Client) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Client) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Client) GetDateOfBirth() int64 {
	if x != nil {
		return x.DateOfBirth
	}
	return 0
}

func (x *Client) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *Client) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Client) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Client) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Client) GetConnectedAccounts() []string {
	if x != nil {
		return x.ConnectedAccounts
	}
	return nil
}

type CreateClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateOfBirth   int64                  `protobuf:"varint,3,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Gender        string                 `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Address       string                 `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClientRequest) Reset() {
	*x = CreateClientRequest{}
	mi := &file_proto_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientRequest) ProtoMessage() {}

func (x *CreateClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClientRequest.ProtoReflect.Descriptor instead.
func (*CreateClientRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{8}
}

func (x *CreateClientRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateClientRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateClientRequest) GetDateOfBirth() int64 {
	if x != nil {
		return x.DateOfBirth
	}
	return 0
}

func (x *CreateClientRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *CreateClientRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateClientRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CreateClientRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint64                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientRequest) Reset() {
	*x = GetClientRequest{}
	mi := &file_proto_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientRequest) ProtoMessage() {}

func (x *GetClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientRequest.ProtoReflect.Descriptor instead.
func (*GetClientRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{9}
}

func (x *GetClientRequest) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type UpdateClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint64                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateOfBirth   int64                  `protobuf:"varint,4,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Gender        string                 `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,7,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Address       string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClientRequest) Reset() {
	*x = UpdateClientRequest{}
	mi := &file_proto_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClientRequest) ProtoMessage() {}

func (x *UpdateClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClientRequest.ProtoReflect.Descriptor instead.
func (*UpdateClientRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateClientRequest) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *UpdateClientRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateClientRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateClientRequest) GetDateOfBirth() int64 {
	if x != nil {
		return x.DateOfBirth
	}
	return 0
}

func (x *UpdateClientRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *UpdateClientRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateClientRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UpdateClientRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type DeleteClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint64                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClientRequest) Reset() {
	*x = DeleteClientRequest{}
	mi := &file_proto_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClientRequest) ProtoMessage() {}

func (x *DeleteClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClientRequest.ProtoReflect.Descriptor instead.
func (*DeleteClientRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteClientRequest) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type ListClientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientsRequest) Reset() {
	*x = ListClientsRequest{}
	mi := &file_proto_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientsRequest) ProtoMessage() {}

func (x *ListClientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientsRequest.ProtoReflect.Descriptor instead.
func (*ListClientsRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{12}
}

type ListClientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clients       []*Client              `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientsResponse) Reset() {
	*x = ListClientsResponse{}
	mi := &file_proto_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientsResponse) ProtoMessage() {}

func (x *ListClientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientsResponse.ProtoReflect.Descriptor instead.
func (*ListClientsResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{13}
}

func (x *ListClientsResponse) GetClients() []*Client {
	if x != nil {
		return x.Clients
	}
	return nil
}

type Permission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_proto_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{14}
}

func (x *Permission) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Permission) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Permission) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ListPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []*Permission          `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsResponse) Reset() {
	*x = ListPermissionsResponse{}
	mi := &file_proto_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsResponse) ProtoMessage() {}

func (x *ListPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsResponse.ProtoReflect.Descriptor instead.
func (*ListPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{15}
}

func (x *ListPermissionsResponse) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

var File_proto_user_proto protoreflect.FileDescriptor

const file_proto_user_proto_rawDesc = "" +
	"\n" +
	"\x10proto/user.proto\x12\x04user\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xf7\x02\n" +
	"\bEmployee\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\"\n" +
	"\rdate_of_birth\x18\x04 \x01(\tR\vdateOfBirth\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\tR\x06gender\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\a \x01(\tR\vphoneNumber\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\x12\x1a\n" +
	"\busername\x18\t \x01(\tR\busername\x12\x1a\n" +
	"\bposition\x18\n" +
	" \x01(\tR\bposition\x12\x1e\n" +
	"\n" +
	"department\x18\v \x01(\tR\n" +
	"department\x12\x16\n" +
	"\x06active\x18\f \x01(\bR\x06active\x12 \n" +
	"\vpermissions\x18\r \x03(\tR\vpermissions\"\xf4\x02\n" +
	"\x15CreateEmployeeRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\"\n" +
	"\rdate_of_birth\x18\x03 \x01(\tR\vdateOfBirth\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\tR\x06gender\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\x06 \x01(\tR\vphoneNumber\x12\x18\n" +
	"\aaddress\x18\a \x01(\tR\aaddress\x12\x1a\n" +
	"\busername\x18\b \x01(\tR\busername\x12\x1a\n" +
	"\bposition\x18\t \x01(\tR\bposition\x12\x1e\n" +
	"\n" +
	"department\x18\n" +
	" \x01(\tR\n" +
	"department\x12\x16\n" +
	"\x06active\x18\v \x01(\bR\x06active\x12 \n" +
	"\vpermissions\x18\f \x03(\tR\vpermissions\"5\n" +
	"\x12GetEmployeeRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\x04R\n" +
	"employeeId\"\xf9\x02\n" +
	"\x15UpdateEmployeeRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\x04R\n" +
	"employeeId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\"\n" +
	"\rdate_of_birth\x18\x04 \x01(\tR\vdateOfBirth\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\tR\x06gender\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\a \x01(\tR\vphoneNumber\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\x12\x1a\n" +
	"\bposition\x18\t \x01(\tR\bposition\x12\x1e\n" +
	"\n" +
	"department\x18\n" +
	" \x01(\tR\n" +
	"department\x12\x16\n" +
	"\x06active\x18\v \x01(\bR\x06active\x12 \n" +
	"\vpermissions\x18\f \x03(\tR\vpermissions\"8\n" +
	"\x15DeleteEmployeeRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\x04R\n" +
	"employeeId\"\x84\x01\n" +
	"\x14ListEmployeesRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\tR\bposition\"E\n" +
	"\x15ListEmployeesResponse\x12,\n" +
	"\temployees\x18\x01 \x03(\v2\x0e.user.EmployeeR\temployees\"\x92\x02\n" +
	"\x06Client\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\"\n" +
	"\rdate_of_birth\x18\x04 \x01(\x03R\vdateOfBirth\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\tR\x06gender\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\a \x01(\tR\vphoneNumber\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\x12-\n" +
	"\x12connected_accounts\x18\t \x03(\tR\x11connectedAccounts\"\xe0\x01\n" +
	"\x13CreateClientRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\"\n" +
	"\rdate_of_birth\x18\x03 \x01(\x03R\vdateOfBirth\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\tR\x06gender\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\x06 \x01(\tR\vphoneNumber\x12\x18\n" +
	"\aaddress\x18\a \x01(\tR\aaddress\"/\n" +
	"\x10GetClientRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\"\xfd\x01\n" +
	"\x13UpdateClientRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\"\n" +
	"\rdate_of_birth\x18\x04 \x01(\x03R\vdateOfBirth\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\tR\x06gender\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\a \x01(\tR\vphoneNumber\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\"2\n" +
	"\x13DeleteClientRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\"\x14\n" +
	"\x12ListClientsRequest\"=\n" +
	"\x13ListClientsResponse\x12&\n" +
	"\aclients\x18\x01 \x03(\v2\f.user.ClientR\aclients\"R\n" +
	"\n" +
	"Permission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"M\n" +
	"\x17ListPermissionsResponse\x122\n" +
	"\vpermissions\x18\x01 \x03(\v2\x10.user.PermissionR\vpermissions2\xf9\a\n" +
	"\vUserService\x12\\\n" +
	"\rListEmployees\x12\x1a.user.ListEmployeesRequest\x1a\x1b.user.ListEmployeesResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/employees\x12T\n" +
	"\x0eCreateEmployee\x12\x1b.user.CreateEmployeeRequest\x1a\x0e.user.Employee\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/employees\x12Y\n" +
	"\vGetEmployee\x12\x18.user.GetEmployeeRequest\x1a\x0e.user.Employee\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/employees/{employee_id}\x12b\n" +
	"\x0eUpdateEmployee\x12\x1b.user.UpdateEmployeeRequest\x1a\x0e.user.Employee\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\x1a\x18/employees/{employee_id}\x12g\n" +
	"\x0eDeleteEmployee\x12\x1b.user.DeleteEmployeeRequest\x1a\x16.google.protobuf.Empty\" \x82\xd3\xe4\x93\x02\x1a*\x18/employees/{employee_id}\x12T\n" +
	"\vListClients\x12\x18.user.ListClientsRequest\x1a\x19.user.ListClientsResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/clients\x12L\n" +
	"\fCreateClient\x12\x19.user.CreateClientRequest\x1a\f.user.Client\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/clients\x12O\n" +
	"\tGetClient\x12\x16.user.GetClientRequest\x1a\f.user.Client\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/clients/{client_id}\x12X\n" +
	"\fUpdateClient\x12\x19.user.UpdateClientRequest\x1a\f.user.Client\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\x1a\x14/clients/{client_id}\x12_\n" +
	"\fDeleteClient\x12\x19.user.DeleteClientRequest\x1a\x16.google.protobuf.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/clients/{client_id}\x12^\n" +
	"\x0fListPermissions\x12\x16.google.protobuf.Empty\x1a\x1d.user.ListPermissionsResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/permissionsB\x12Z\x10user-service/pb/b\x06proto3"

var (
	file_proto_user_proto_rawDescOnce sync.Once
	file_proto_user_proto_rawDescData []byte
)

func file_proto_user_proto_rawDescGZIP() []byte {
	file_proto_user_proto_rawDescOnce.Do(func() {
		file_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_proto_rawDesc), len(file_proto_user_proto_rawDesc)))
	})
	return file_proto_user_proto_rawDescData
}

var file_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_user_proto_goTypes = []any{
	(*Employee)(nil),                // 0: user.Employee
	(*CreateEmployeeRequest)(nil),   // 1: user.CreateEmployeeRequest
	(*GetEmployeeRequest)(nil),      // 2: user.GetEmployeeRequest
	(*UpdateEmployeeRequest)(nil),   // 3: user.UpdateEmployeeRequest
	(*DeleteEmployeeRequest)(nil),   // 4: user.DeleteEmployeeRequest
	(*ListEmployeesRequest)(nil),    // 5: user.ListEmployeesRequest
	(*ListEmployeesResponse)(nil),   // 6: user.ListEmployeesResponse
	(*Client)(nil),                  // 7: user.Client
	(*CreateClientRequest)(nil),     // 8: user.CreateClientRequest
	(*GetClientRequest)(nil),        // 9: user.GetClientRequest
	(*UpdateClientRequest)(nil),     // 10: user.UpdateClientRequest
	(*DeleteClientRequest)(nil),     // 11: user.DeleteClientRequest
	(*ListClientsRequest)(nil),      // 12: user.ListClientsRequest
	(*ListClientsResponse)(nil),     // 13: user.ListClientsResponse
	(*Permission)(nil),              // 14: user.Permission
	(*ListPermissionsResponse)(nil), // 15: user.ListPermissionsResponse
	(*emptypb.Empty)(nil),           // 16: google.protobuf.Empty
}
var file_proto_user_proto_depIdxs = []int32{
	0,  // 0: user.ListEmployeesResponse.employees:type_name -> user.Employee
	7,  // 1: user.ListClientsResponse.clients:type_name -> user.Client
	14, // 2: user.ListPermissionsResponse.permissions:type_name -> user.Permission
	5,  // 3: user.UserService.ListEmployees:input_type -> user.ListEmployeesRequest
	1,  // 4: user.UserService.CreateEmployee:input_type -> user.CreateEmployeeRequest
	2,  // 5: user.UserService.GetEmployee:input_type -> user.GetEmployeeRequest
	3,  // 6: user.UserService.UpdateEmployee:input_type -> user.UpdateEmployeeRequest
	4,  // 7: user.UserService.DeleteEmployee:input_type -> user.DeleteEmployeeRequest
	12, // 8: user.UserService.ListClients:input_type -> user.ListClientsRequest
	8,  // 9: user.UserService.CreateClient:input_type -> user.CreateClientRequest
	9,  // 10: user.UserService.GetClient:input_type -> user.GetClientRequest
	10, // 11: user.UserService.UpdateClient:input_type -> user.UpdateClientRequest
	11, // 12: user.UserService.DeleteClient:input_type -> user.DeleteClientRequest
	16, // 13: user.UserService.ListPermissions:input_type -> google.protobuf.Empty
	6,  // 14: user.UserService.ListEmployees:output_type -> user.ListEmployeesResponse
	0,  // 15: user.UserService.CreateEmployee:output_type -> user.Employee
	0,  // 16: user.UserService.GetEmployee:output_type -> user.Employee
	0,  // 17: user.UserService.UpdateEmployee:output_type -> user.Employee
	16, // 18: user.UserService.DeleteEmployee:output_type -> google.protobuf.Empty
	13, // 19: user.UserService.ListClients:output_type -> user.ListClientsResponse
	7,  // 20: user.UserService.CreateClient:output_type -> user.Client
	7,  // 21: user.UserService.GetClient:output_type -> user.Client
	7,  // 22: user.UserService.UpdateClient:output_type -> user.Client
	16, // 23: user.UserService.DeleteClient:output_type -> google.protobuf.Empty
	15, // 24: user.UserService.ListPermissions:output_type -> user.ListPermissionsResponse
	14, // [14:25] is the sub-list for method output_type
	3,  // [3:14] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_user_proto_init() }
func file_proto_user_proto_init() {
	if File_proto_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_proto_rawDesc), len(file_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_proto_goTypes,
		DependencyIndexes: file_proto_user_proto_depIdxs,
		MessageInfos:      file_proto_user_proto_msgTypes,
	}.Build()
	File_proto_user_proto = out.File
	file_proto_user_proto_goTypes = nil
	file_proto_user_proto_depIdxs = nil
}
