// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: trading/external_otc.proto

package trading

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExternalOTCThread struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Direction          string                 `protobuf:"bytes,2,opt,name=direction,proto3" json:"direction,omitempty"`
	RemoteBankCode     string                 `protobuf:"bytes,3,opt,name=remote_bank_code,json=remoteBankCode,proto3" json:"remote_bank_code,omitempty"`
	RemoteThreadId     string                 `protobuf:"bytes,4,opt,name=remote_thread_id,json=remoteThreadId,proto3" json:"remote_thread_id,omitempty"`
	RemoteUserRef      string                 `protobuf:"bytes,5,opt,name=remote_user_ref,json=remoteUserRef,proto3" json:"remote_user_ref,omitempty"`
	RemoteDisplayName  string                 `protobuf:"bytes,6,opt,name=remote_display_name,json=remoteDisplayName,proto3" json:"remote_display_name,omitempty"`
	RemoteAccountRef   string                 `protobuf:"bytes,7,opt,name=remote_account_ref,json=remoteAccountRef,proto3" json:"remote_account_ref,omitempty"`
	LocalUserId        string                 `protobuf:"bytes,8,opt,name=local_user_id,json=localUserId,proto3" json:"local_user_id,omitempty"`
	LocalUserKind      string                 `protobuf:"bytes,9,opt,name=local_user_kind,json=localUserKind,proto3" json:"local_user_kind,omitempty"`
	LocalAccountId     string                 `protobuf:"bytes,10,opt,name=local_account_id,json=localAccountId,proto3" json:"local_account_id,omitempty"`
	LocalAccountNumber string                 `protobuf:"bytes,11,opt,name=local_account_number,json=localAccountNumber,proto3" json:"local_account_number,omitempty"`
	LocalRole          string                 `protobuf:"bytes,12,opt,name=local_role,json=localRole,proto3" json:"local_role,omitempty"`
	SecurityId         string                 `protobuf:"bytes,13,opt,name=security_id,json=securityId,proto3" json:"security_id,omitempty"`
	SecurityTicker     string                 `protobuf:"bytes,14,opt,name=security_ticker,json=securityTicker,proto3" json:"security_ticker,omitempty"`
	SellerHoldingId    string                 `protobuf:"bytes,15,opt,name=seller_holding_id,json=sellerHoldingId,proto3" json:"seller_holding_id,omitempty"`
	Quantity           int64                  `protobuf:"varint,16,opt,name=quantity,proto3" json:"quantity,omitempty"`
	PricePerUnit       string                 `protobuf:"bytes,17,opt,name=price_per_unit,json=pricePerUnit,proto3" json:"price_per_unit,omitempty"`
	Premium            string                 `protobuf:"bytes,18,opt,name=premium,proto3" json:"premium,omitempty"`
	Currency           string                 `protobuf:"bytes,19,opt,name=currency,proto3" json:"currency,omitempty"`
	SettlementDate     string                 `protobuf:"bytes,20,opt,name=settlement_date,json=settlementDate,proto3" json:"settlement_date,omitempty"`
	ModifiedBySide     string                 `protobuf:"bytes,21,opt,name=modified_by_side,json=modifiedBySide,proto3" json:"modified_by_side,omitempty"`
	Status             string                 `protobuf:"bytes,22,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,23,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          string                 `protobuf:"bytes,24,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ExternalOTCThread) Reset() {
	*x = ExternalOTCThread{}
	mi := &file_trading_external_otc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalOTCThread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalOTCThread) ProtoMessage() {}

func (x *ExternalOTCThread) ProtoReflect() protoreflect.Message {
	mi := &file_trading_external_otc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalOTCThread.ProtoReflect.Descriptor instead.
func (*ExternalOTCThread) Descriptor() ([]byte, []int) {
	return file_trading_external_otc_proto_rawDescGZIP(), []int{0}
}

func (x *ExternalOTCThread) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExternalOTCThread) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *ExternalOTCThread) GetRemoteBankCode() string {
	if x != nil {
		return x.RemoteBankCode
	}
	return ""
}

func (x *ExternalOTCThread) GetRemoteThreadId() string {
	if x != nil {
		return x.RemoteThreadId
	}
	return ""
}

func (x *ExternalOTCThread) GetRemoteUserRef() string {
	if x != nil {
		return x.RemoteUserRef
	}
	return ""
}

func (x *ExternalOTCThread) GetRemoteDisplayName() string {
	if x != nil {
		return x.RemoteDisplayName
	}
	return ""
}

func (x *ExternalOTCThread) GetRemoteAccountRef() string {
	if x != nil {
		return x.RemoteAccountRef
	}
	return ""
}

func (x *ExternalOTCThread) GetLocalUserId() string {
	if x != nil {
		return x.LocalUserId
	}
	return ""
}

func (x *ExternalOTCThread) GetLocalUserKind() string {
	if x != nil {
		return x.LocalUserKind
	}
	return ""
}

func (x *ExternalOTCThread) GetLocalAccountId() string {
	if x != nil {
		return x.LocalAccountId
	}
	return ""
}

func (x *ExternalOTCThread) GetLocalAccountNumber() string {
	if x != nil {
		return x.LocalAccountNumber
	}
	return ""
}

func (x *ExternalOTCThread) GetLocalRole() string {
	if x != nil {
		return x.LocalRole
	}
	return ""
}

func (x *ExternalOTCThread) GetSecurityId() string {
	if x != nil {
		return x.SecurityId
	}
	return ""
}

func (x *ExternalOTCThread) GetSecurityTicker() string {
	if x != nil {
		return x.SecurityTicker
	}
	return ""
}

func (x *ExternalOTCThread) GetSellerHoldingId() string {
	if x != nil {
		return x.SellerHoldingId
	}
	return ""
}

func (x *ExternalOTCThread) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ExternalOTCThread) GetPricePerUnit() string {
	if x != nil {
		return x.PricePerUnit
	}
	return ""
}

func (x *ExternalOTCThread) GetPremium() string {
	if x != nil {
		return x.Premium
	}
	return ""
}

func (x *ExternalOTCThread) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ExternalOTCThread) GetSettlementDate() string {
	if x != nil {
		return x.SettlementDate
	}
	return ""
}

func (x *ExternalOTCThread) GetModifiedBySide() string {
	if x != nil {
		return x.ModifiedBySide
	}
	return ""
}

func (x *ExternalOTCThread) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExternalOTCThread) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ExternalOTCThread) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ExternalOTCIteration struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ThreadId       string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	ProposedBySide string                 `protobuf:"bytes,3,opt,name=proposed_by_side,json=proposedBySide,proto3" json:"proposed_by_side,omitempty"`
	Quantity       int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	PricePerUnit   string                 `protobuf:"bytes,5,opt,name=price_per_unit,json=pricePerUnit,proto3" json:"price_per_unit,omitempty"`
	Premium        string                 `protobuf:"bytes,6,opt,name=premium,proto3" json:"premium,omitempty"`
	SettlementDate string                 `protobuf:"bytes,7,opt,name=settlement_date,json=settlementDate,proto3" json:"settlement_date,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExternalOTCIteration) Reset() {
	*x = ExternalOTCIteration{}
	mi := &file_trading_external_otc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalOTCIteration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalOTCIteration) ProtoMessage() {}

func (x *ExternalOTCIteration) ProtoReflect() protoreflect.Message {
	mi := &file_trading_external_otc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalOTCIteration.ProtoReflect.Descriptor instead.
func (*ExternalOTCIteration) Descriptor() ([]byte, []int) {
	return file_trading_external_otc_proto_rawDescGZIP(), []int{1}
}

func (x *ExternalOTCIteration) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExternalOTCIteration) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *ExternalOTCIteration) GetProposedBySide() string {
	if x != nil {
		return x.ProposedBySide
	}
	return ""
}

func (x *ExternalOTCIteration) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ExternalOTCIteration) GetPricePerUnit() string {
	if x != nil {
		return x.PricePerUnit
	}
	return ""
}

func (x *ExternalOTCIteration) GetPremium() string {
	if x != nil {
		return x.Premium
	}
	return ""
}

func (x *ExternalOTCIteration) GetSettlementDate() string {
	if x != nil {
		return x.SettlementDate
	}
	return ""
}

func (x *ExternalOTCIteration) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ExternalOTCContract struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ThreadId           string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	Direction          string                 `protobuf:"bytes,3,opt,name=direction,proto3" json:"direction,omitempty"`
	RemoteBankCode     string                 `protobuf:"bytes,4,opt,name=remote_bank_code,json=remoteBankCode,proto3" json:"remote_bank_code,omitempty"`
	RemoteThreadId     string                 `protobuf:"bytes,5,opt,name=remote_thread_id,json=remoteThreadId,proto3" json:"remote_thread_id,omitempty"`
	RemoteUserRef      string                 `protobuf:"bytes,6,opt,name=remote_user_ref,json=remoteUserRef,proto3" json:"remote_user_ref,omitempty"`
	RemoteDisplayName  string                 `protobuf:"bytes,7,opt,name=remote_display_name,json=remoteDisplayName,proto3" json:"remote_display_name,omitempty"`
	RemoteAccountRef   string                 `protobuf:"bytes,8,opt,name=remote_account_ref,json=remoteAccountRef,proto3" json:"remote_account_ref,omitempty"`
	LocalUserId        string                 `protobuf:"bytes,9,opt,name=local_user_id,json=localUserId,proto3" json:"local_user_id,omitempty"`
	LocalUserKind      string                 `protobuf:"bytes,10,opt,name=local_user_kind,json=localUserKind,proto3" json:"local_user_kind,omitempty"`
	LocalAccountId     string                 `protobuf:"bytes,11,opt,name=local_account_id,json=localAccountId,proto3" json:"local_account_id,omitempty"`
	LocalAccountNumber string                 `protobuf:"bytes,12,opt,name=local_account_number,json=localAccountNumber,proto3" json:"local_account_number,omitempty"`
	LocalRole          string                 `protobuf:"bytes,13,opt,name=local_role,json=localRole,proto3" json:"local_role,omitempty"`
	SecurityId         string                 `protobuf:"bytes,14,opt,name=security_id,json=securityId,proto3" json:"security_id,omitempty"`
	SecurityTicker     string                 `protobuf:"bytes,15,opt,name=security_ticker,json=securityTicker,proto3" json:"security_ticker,omitempty"`
	SellerHoldingId    string                 `protobuf:"bytes,16,opt,name=seller_holding_id,json=sellerHoldingId,proto3" json:"seller_holding_id,omitempty"`
	Quantity           int64                  `protobuf:"varint,17,opt,name=quantity,proto3" json:"quantity,omitempty"`
	StrikePrice        string                 `protobuf:"bytes,18,opt,name=strike_price,json=strikePrice,proto3" json:"strike_price,omitempty"`
	PremiumPaid        string                 `protobuf:"bytes,19,opt,name=premium_paid,json=premiumPaid,proto3" json:"premium_paid,omitempty"`
	Currency           string                 `protobuf:"bytes,20,opt,name=currency,proto3" json:"currency,omitempty"`
	SettlementDate     string                 `protobuf:"bytes,21,opt,name=settlement_date,json=settlementDate,proto3" json:"settlement_date,omitempty"`
	AcceptedBySide     string                 `protobuf:"bytes,22,opt,name=accepted_by_side,json=acceptedBySide,proto3" json:"accepted_by_side,omitempty"`
	Status             string                 `protobuf:"bytes,23,opt,name=status,proto3" json:"status,omitempty"`
	PremiumOpId        string                 `protobuf:"bytes,24,opt,name=premium_op_id,json=premiumOpId,proto3" json:"premium_op_id,omitempty"`
	ExerciseOpId       string                 `protobuf:"bytes,25,opt,name=exercise_op_id,json=exerciseOpId,proto3" json:"exercise_op_id,omitempty"`
	ExercisedAt        string                 `protobuf:"bytes,26,opt,name=exercised_at,json=exercisedAt,proto3" json:"exercised_at,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,27,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          string                 `protobuf:"bytes,28,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ExternalOTCContract) Reset() {
	*x = ExternalOTCContract{}
	mi := &file_trading_external_otc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalOTCContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalOTCContract) ProtoMessage() {}

func (x *ExternalOTCContract) ProtoReflect() protoreflect.Message {
	mi := &file_trading_external_otc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalOTCContract.ProtoReflect.Descriptor instead.
func (*ExternalOTCContract) Descriptor() ([]byte, []int) {
	return file_trading_external_otc_proto_rawDescGZIP(), []int{2}
}

func (x *ExternalOTCContract) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExternalOTCContract) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *ExternalOTCContract) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *ExternalOTCContract) GetRemoteBankCode() string {
	if x != nil {
		return x.RemoteBankCode
	}
	return ""
}

func (x *ExternalOTCContract) GetRemoteThreadId() string {
	if x != nil {
		return x.RemoteThreadId
	}
	return ""
}

func (x *ExternalOTCContract) GetRemoteUserRef() string {
	if x != nil {
		return x.RemoteUserRef
	}
	return ""
}

func (x *ExternalOTCContract) GetRemoteDisplayName() string {
	if x != nil {
		return x.RemoteDisplayName
	}
	return ""
}

func (x *ExternalOTCContract) GetRemoteAccountRef() string {
	if x != nil {
		return x.RemoteAccountRef
	}
	return ""
}

func (x *ExternalOTCContract) GetLocalUserId() string {
	if x != nil {
		return x.LocalUserId
	}
	return ""
}

func (x *ExternalOTCContract) GetLocalUserKind() string {
	if x != nil {
		return x.LocalUserKind
	}
	return ""
}

func (x *ExternalOTCContract) GetLocalAccountId() string {
	if x != nil {
		return x.LocalAccountId
	}
	return ""
}

func (x *ExternalOTCContract) GetLocalAccountNumber() string {
	if x != nil {
		return x.LocalAccountNumber
	}
	return ""
}

func (x *ExternalOTCContract) GetLocalRole() string {
	if x != nil {
		return x.LocalRole
	}
	return ""
}

func (x *ExternalOTCContract) GetSecurityId() string {
	if x != nil {
		return x.SecurityId
	}
	return ""
}

func (x *ExternalOTCContract) GetSecurityTicker() string {
	if x != nil {
		return x.SecurityTicker
	}
	return ""
}

func (x *ExternalOTCContract) GetSellerHoldingId() string {
	if x != nil {
		return x.SellerHoldingId
	}
	return ""
}

func (x *ExternalOTCContract) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ExternalOTCContract) GetStrikePrice() string {
	if x != nil {
		return x.StrikePrice
	}
	return ""
}

func (x *ExternalOTCContract) GetPremiumPaid() string {
	if x != nil {
		return x.PremiumPaid
	}
	return ""
}

func (x *ExternalOTCContract) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ExternalOTCContract) GetSettlementDate() string {
	if x != nil {
		return x.SettlementDate
	}
	return ""
}

func (x *ExternalOTCContract) GetAcceptedBySide() string {
	if x != nil {
		return x.AcceptedBySide
	}
	return ""
}

func (x *ExternalOTCContract) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExternalOTCContract) GetPremiumOpId() string {
	if x != nil {
		return x.PremiumOpId
	}
	return ""
}

func (x *ExternalOTCContract) GetExerciseOpId() string {
	if x != nil {
		return x.ExerciseOpId
	}
	return ""
}

func (x *ExternalOTCContract) GetExercisedAt() string {
	if x != nil {
		return x.ExercisedAt
	}
	return ""
}

func (x *ExternalOTCContract) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ExternalOTCContract) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListExternalOTCThreadsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExternalOTCThreadsRequest) Reset() {
	*x = ListExternalOTCThreadsRequest{}
	mi := &file_trading_external_otc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExternalOTCThreadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExternalOTCThreadsRequest) ProtoMessage() {}

func (x *ListExternalOTCThreadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_external_otc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExternalOTCThreadsRequest.ProtoReflect.Descriptor instead.
func (*ListExternalOTCThreadsRequest) Descriptor() ([]byte, []int) {
	return file_trading_external_otc_proto_rawDescGZIP(), []int{3}
}

func (x *ListExternalOTCThreadsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListExternalOTCThreadsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Threads       []*ExternalOTCThread   `protobuf:"bytes,1,rep,name=threads,proto3" json:"threads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExternalOTCThreadsResponse) Reset() {
	*x = ListExternalOTCThreadsResponse{}
	mi := &file_trading_external_otc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExternalOTCThreadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExternalOTCThreadsResponse) ProtoMessage() {}

func (x *ListExternalOTCThreadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_external_otc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExternalOTCThreadsResponse.ProtoReflect.Descriptor instead.
func (*ListExternalOTCThreadsResponse) Descriptor() ([]byte, []int) {
	return file_trading_external_otc_proto_rawDescGZIP(), []int{4}
}

func (x *ListExternalOTCThreadsResponse) GetThreads() []*ExternalOTCThread {
	if x != nil {
		return x.Threads
	}
	return nil
}

type GetExternalOTCThreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExternalOTCThreadRequest) Reset() {
	*x = GetExternalOTCThreadRequest{}
	mi := &file_trading_external_otc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExternalOTCThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExternalOTCThreadRequest) ProtoMessage() {}

func (x *GetExternalOTCThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_external_otc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExternalOTCThreadRequest.ProtoReflect.Descriptor instead.
func (*GetExternalOTCThreadRequest) Descriptor() ([]byte, []int) {
	return file_trading_external_otc_proto_rawDescGZIP(), []int{5}
}

func (x *GetExternalOTCThreadRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

type GetExternalOTCThreadResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Thread        *ExternalOTCThread      `protobuf:"bytes,1,opt,name=thread,proto3" json:"thread,omitempty"`
	Iterations    []*ExternalOTCIteration `protobuf:"bytes,2,rep,name=iterations,proto3" json:"iterations,omitempty"`
	Contract      *ExternalOTCContract    `protobuf:"bytes,3,opt,name=contract,proto3" json:"contract,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExternalOTCThreadResponse) Reset() {
	*x = GetExternalOTCThreadResponse{}
	mi := &file_trading_external_otc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExternalOTCThreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExternalOTCThreadResponse) ProtoMessage() {}

func (x *GetExternalOTCThreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_external_otc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExternalOTCThreadResponse.ProtoReflect.Descriptor instead.
func (*GetExternalOTCThreadResponse) Descriptor() ([]byte, []int) {
	return file_trading_external_otc_proto_rawDescGZIP(), []int{6}
}

func (x *GetExternalOTCThreadResponse) GetThread() *ExternalOTCThread {
	if x != nil {
		return x.Thread
	}
	return nil
}

func (x *GetExternalOTCThreadResponse) GetIterations() []*ExternalOTCIteration {
	if x != nil {
		return x.Iterations
	}
	return nil
}

func (x *GetExternalOTCThreadResponse) GetContract() *ExternalOTCContract {
	if x != nil {
		return x.Contract
	}
	return nil
}

type CreateExternalOTCOfferRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RemoteBankCode    string                 `protobuf:"bytes,1,opt,name=remote_bank_code,json=remoteBankCode,proto3" json:"remote_bank_code,omitempty"`
	RemoteUserRef     string                 `protobuf:"bytes,2,opt,name=remote_user_ref,json=remoteUserRef,proto3" json:"remote_user_ref,omitempty"`
	RemoteDisplayName string                 `protobuf:"bytes,3,opt,name=remote_display_name,json=remoteDisplayName,proto3" json:"remote_display_name,omitempty"`
	BuyerAccountId    string                 `protobuf:"bytes,4,opt,name=buyer_account_id,json=buyerAccountId,proto3" json:"buyer_account_id,omitempty"`
	SellerHoldingId   string                 `protobuf:"bytes,5,opt,name=seller_holding_id,json=sellerHoldingId,proto3" json:"seller_holding_id,omitempty"`
	SecurityTicker    string                 `protobuf:"bytes,6,opt,name=security_ticker,json=securityTicker,proto3" json:"security_ticker,omitempty"`
	SecurityType      string                 `protobuf:"bytes,7,opt,name=security_type,json=securityType,proto3" json:"security_type,omitempty"`
	Currency          string                 `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	Quantity          int64                  `protobuf:"varint,9,opt,name=quantity,proto3" json:"quantity,omitempty"`
	PricePerUnit      string                 `protobuf:"bytes,10,opt,name=price_per_unit,json=pricePerUnit,proto3" json:"price_per_unit,omitempty"`
	Premium           string                 `protobuf:"bytes,11,opt,name=premium,proto3" json:"premium,omitempty"`
	SettlementDate    string                 `protobuf:"bytes,12,opt,name=settlement_date,json=settlementDate,proto3" json:"settlement_date,omitempty"`
	RemoteThreadId    string                 `protobuf:"bytes,13,opt,name=remote_thread_id,json=remoteThreadId,proto3" json:"remote_thread_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateExternalOTCOfferRequest) Reset() {
	*x = CreateExternalOTCOfferRequest{}
	mi := &file_trading_external_otc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExternalOTCOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExternalOTCOfferRequest) ProtoMessage() {}

func (x *CreateExternalOTCOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_external_otc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExternalOTCOfferRequest.ProtoReflect.Descriptor instead.
func (*CreateExternalOTCOfferRequest) Descriptor() ([]byte, []int) {
	return file_trading_external_otc_proto_rawDescGZIP(), []int{7}
}

func (x *CreateExternalOTCOfferRequest) GetRemoteBankCode() string {
	if x != nil {
		return x.RemoteBankCode
	}
	return ""
}

func (x *CreateExternalOTCOfferRequest) GetRemoteUserRef() string {
	if x != nil {
		return x.RemoteUserRef
	}
	return ""
}

func (x *CreateExternalOTCOfferRequest) GetRemoteDisplayName() string {
	if x != nil {
		return x.RemoteDisplayName
	}
	return ""
}

func (x *CreateExternalOTCOfferRequest) GetBuyerAccountId() string {
	if x != nil {
		return x.BuyerAccountId
	}
	return ""
}

func (x *CreateExternalOTCOfferRequest) GetSellerHoldingId() string {
	if x != nil {
		return x.SellerHoldingId
	}
	return ""
}

func (x *CreateExternalOTCOfferRequest) GetSecurityTicker() string {
	if x != nil {
		return x.SecurityTicker
	}
	return ""
}

func (x *CreateExternalOTCOfferRequest) GetSecurityType() string {
	if x != nil {
		return x.SecurityType
	}
	return ""
}

func (x *CreateExternalOTCOfferRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateExternalOTCOfferRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateExternalOTCOfferRequest) GetPricePerUnit() string {
	if x != nil {
		return x.PricePerUnit
	}
	return ""
}

func (x *CreateExternalOTCOfferRequest) GetPremium() string {
	if x != nil {
		return x.Premium
	}
	return ""
}

func (x *CreateExternalOTCOfferRequest) GetSettlementDate() string {
	if x != nil {
		return x.SettlementDate
	}
	return ""
}

func (x *CreateExternalOTCOfferRequest) GetRemoteThreadId() string {
	if x != nil {
		return x.RemoteThreadId
	}
	return ""
}

type CreateExternalOTCOfferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocalMirror   *ExternalOTCThread     `protobuf:"bytes,1,opt,name=local_mirror,json=localMirror,proto3" json:"local_mirror,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExternalOTCOfferResponse) Reset() {
	*x = CreateExternalOTCOfferResponse{}
	mi := &file_trading_external_otc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExternalOTCOfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExternalOTCOfferResponse) ProtoMessage() {}

func (x *CreateExternalOTCOfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_external_otc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExternalOTCOfferResponse.ProtoReflect.Descriptor instead.
func (*CreateExternalOTCOfferResponse) Descriptor() ([]byte, []int) {
	return file_trading_external_otc_proto_rawDescGZIP(), []int{8}
}

func (x *CreateExternalOTCOfferResponse) GetLocalMirror() *ExternalOTCThread {
	if x != nil {
		return x.LocalMirror
	}
	return nil
}

type ExternalOTCActionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BankCode       string                 `protobuf:"bytes,1,opt,name=bank_code,json=bankCode,proto3" json:"bank_code,omitempty"`
	ThreadId       string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	Quantity       int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	PricePerUnit   string                 `protobuf:"bytes,4,opt,name=price_per_unit,json=pricePerUnit,proto3" json:"price_per_unit,omitempty"`
	Premium        string                 `protobuf:"bytes,5,opt,name=premium,proto3" json:"premium,omitempty"`
	SettlementDate string                 `protobuf:"bytes,6,opt,name=settlement_date,json=settlementDate,proto3" json:"settlement_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExternalOTCActionRequest) Reset() {
	*x = ExternalOTCActionRequest{}
	mi := &file_trading_external_otc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalOTCActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalOTCActionRequest) ProtoMessage() {}

func (x *ExternalOTCActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_external_otc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalOTCActionRequest.ProtoReflect.Descriptor instead.
func (*ExternalOTCActionRequest) Descriptor() ([]byte, []int) {
	return file_trading_external_otc_proto_rawDescGZIP(), []int{9}
}

func (x *ExternalOTCActionRequest) GetBankCode() string {
	if x != nil {
		return x.BankCode
	}
	return ""
}

func (x *ExternalOTCActionRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *ExternalOTCActionRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ExternalOTCActionRequest) GetPricePerUnit() string {
	if x != nil {
		return x.PricePerUnit
	}
	return ""
}

func (x *ExternalOTCActionRequest) GetPremium() string {
	if x != nil {
		return x.Premium
	}
	return ""
}

func (x *ExternalOTCActionRequest) GetSettlementDate() string {
	if x != nil {
		return x.SettlementDate
	}
	return ""
}

type ExternalOTCActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Thread        *ExternalOTCThread     `protobuf:"bytes,1,opt,name=thread,proto3" json:"thread,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalOTCActionResponse) Reset() {
	*x = ExternalOTCActionResponse{}
	mi := &file_trading_external_otc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalOTCActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalOTCActionResponse) ProtoMessage() {}

func (x *ExternalOTCActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_external_otc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalOTCActionResponse.ProtoReflect.Descriptor instead.
func (*ExternalOTCActionResponse) Descriptor() ([]byte, []int) {
	return file_trading_external_otc_proto_rawDescGZIP(), []int{10}
}

func (x *ExternalOTCActionResponse) GetThread() *ExternalOTCThread {
	if x != nil {
		return x.Thread
	}
	return nil
}

type ListExternalOTCContractsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExternalOTCContractsRequest) Reset() {
	*x = ListExternalOTCContractsRequest{}
	mi := &file_trading_external_otc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExternalOTCContractsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExternalOTCContractsRequest) ProtoMessage() {}

func (x *ListExternalOTCContractsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_external_otc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExternalOTCContractsRequest.ProtoReflect.Descriptor instead.
func (*ListExternalOTCContractsRequest) Descriptor() ([]byte, []int) {
	return file_trading_external_otc_proto_rawDescGZIP(), []int{11}
}

func (x *ListExternalOTCContractsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListExternalOTCContractsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contracts     []*ExternalOTCContract `protobuf:"bytes,1,rep,name=contracts,proto3" json:"contracts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExternalOTCContractsResponse) Reset() {
	*x = ListExternalOTCContractsResponse{}
	mi := &file_trading_external_otc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExternalOTCContractsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExternalOTCContractsResponse) ProtoMessage() {}

func (x *ListExternalOTCContractsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_external_otc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExternalOTCContractsResponse.ProtoReflect.Descriptor instead.
func (*ListExternalOTCContractsResponse) Descriptor() ([]byte, []int) {
	return file_trading_external_otc_proto_rawDescGZIP(), []int{12}
}

func (x *ListExternalOTCContractsResponse) GetContracts() []*ExternalOTCContract {
	if x != nil {
		return x.Contracts
	}
	return nil
}

type ExerciseExternalOTCContractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BankCode      string                 `protobuf:"bytes,1,opt,name=bank_code,json=bankCode,proto3" json:"bank_code,omitempty"`
	ContractId    string                 `protobuf:"bytes,2,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	ExerciseOpId  string                 `protobuf:"bytes,3,opt,name=exercise_op_id,json=exerciseOpId,proto3" json:"exercise_op_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExerciseExternalOTCContractRequest) Reset() {
	*x = ExerciseExternalOTCContractRequest{}
	mi := &file_trading_external_otc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExerciseExternalOTCContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExerciseExternalOTCContractRequest) ProtoMessage() {}

func (x *ExerciseExternalOTCContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_external_otc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExerciseExternalOTCContractRequest.ProtoReflect.Descriptor instead.
func (*ExerciseExternalOTCContractRequest) Descriptor() ([]byte, []int) {
	return file_trading_external_otc_proto_rawDescGZIP(), []int{13}
}

func (x *ExerciseExternalOTCContractRequest) GetBankCode() string {
	if x != nil {
		return x.BankCode
	}
	return ""
}

func (x *ExerciseExternalOTCContractRequest) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *ExerciseExternalOTCContractRequest) GetExerciseOpId() string {
	if x != nil {
		return x.ExerciseOpId
	}
	return ""
}

type ExerciseExternalOTCContractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contract      *ExternalOTCContract   `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExerciseExternalOTCContractResponse) Reset() {
	*x = ExerciseExternalOTCContractResponse{}
	mi := &file_trading_external_otc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExerciseExternalOTCContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExerciseExternalOTCContractResponse) ProtoMessage() {}

func (x *ExerciseExternalOTCContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_external_otc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExerciseExternalOTCContractResponse.ProtoReflect.Descriptor instead.
func (*ExerciseExternalOTCContractResponse) Descriptor() ([]byte, []int) {
	return file_trading_external_otc_proto_rawDescGZIP(), []int{14}
}

func (x *ExerciseExternalOTCContractResponse) GetContract() *ExternalOTCContract {
	if x != nil {
		return x.Contract
	}
	return nil
}

var File_trading_external_otc_proto protoreflect.FileDescriptor

const file_trading_external_otc_proto_rawDesc = "" +
	"\n" +
	"\x1atrading/external_otc.proto\x12\atrading\"\xf9\x06\n" +
	"\x11ExternalOTCThread\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tdirection\x18\x02 \x01(\tR\tdirection\x12(\n" +
	"\x10remote_bank_code\x18\x03 \x01(\tR\x0eremoteBankCode\x12(\n" +
	"\x10remote_thread_id\x18\x04 \x01(\tR\x0eremoteThreadId\x12&\n" +
	"\x0fremote_user_ref\x18\x05 \x01(\tR\rremoteUserRef\x12.\n" +
	"\x13remote_display_name\x18\x06 \x01(\tR\x11remoteDisplayName\x12,\n" +
	"\x12remote_account_ref\x18\a \x01(\tR\x10remoteAccountRef\x12\"\n" +
	"\rlocal_user_id\x18\b \x01(\tR\vlocalUserId\x12&\n" +
	"\x0flocal_user_kind\x18\t \x01(\tR\rlocalUserKind\x12(\n" +
	"\x10local_account_id\x18\n" +
	" \x01(\tR\x0elocalAccountId\x120\n" +
	"\x14local_account_number\x18\v \x01(\tR\x12localAccountNumber\x12\x1d\n" +
	"\n" +
	"local_role\x18\f \x01(\tR\tlocalRole\x12\x1f\n" +
	"\vsecurity_id\x18\r \x01(\tR\n" +
	"securityId\x12'\n" +
	"\x0fsecurity_ticker\x18\x0e \x01(\tR\x0esecurityTicker\x12*\n" +
	"\x11seller_holding_id\x18\x0f \x01(\tR\x0fsellerHoldingId\x12\x1a\n" +
	"\bquantity\x18\x10 \x01(\x03R\bquantity\x12$\n" +
	"\x0eprice_per_unit\x18\x11 \x01(\tR\fpricePerUnit\x12\x18\n" +
	"\apremium\x18\x12 \x01(\tR\apremium\x12\x1a\n" +
	"\bcurrency\x18\x13 \x01(\tR\bcurrency\x12'\n" +
	"\x0fsettlement_date\x18\x14 \x01(\tR\x0esettlementDate\x12(\n" +
	"\x10modified_by_side\x18\x15 \x01(\tR\x0emodifiedBySide\x12\x16\n" +
	"\x06status\x18\x16 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x17 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x18 \x01(\tR\tupdatedAt\"\x91\x02\n" +
	"\x14ExternalOTCIteration\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\x12(\n" +
	"\x10proposed_by_side\x18\x03 \x01(\tR\x0eproposedBySide\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\x12$\n" +
	"\x0eprice_per_unit\x18\x05 \x01(\tR\fpricePerUnit\x12\x18\n" +
	"\apremium\x18\x06 \x01(\tR\apremium\x12'\n" +
	"\x0fsettlement_date\x18\a \x01(\tR\x0esettlementDate\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\"\x8b\b\n" +
	"\x13ExternalOTCContract\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\x12\x1c\n" +
	"\tdirection\x18\x03 \x01(\tR\tdirection\x12(\n" +
	"\x10remote_bank_code\x18\x04 \x01(\tR\x0eremoteBankCode\x12(\n" +
	"\x10remote_thread_id\x18\x05 \x01(\tR\x0eremoteThreadId\x12&\n" +
	"\x0fremote_user_ref\x18\x06 \x01(\tR\rremoteUserRef\x12.\n" +
	"\x13remote_display_name\x18\a \x01(\tR\x11remoteDisplayName\x12,\n" +
	"\x12remote_account_ref\x18\b \x01(\tR\x10remoteAccountRef\x12\"\n" +
	"\rlocal_user_id\x18\t \x01(\tR\vlocalUserId\x12&\n" +
	"\x0flocal_user_kind\x18\n" +
	" \x01(\tR\rlocalUserKind\x12(\n" +
	"\x10local_account_id\x18\v \x01(\tR\x0elocalAccountId\x120\n" +
	"\x14local_account_number\x18\f \x01(\tR\x12localAccountNumber\x12\x1d\n" +
	"\n" +
	"local_role\x18\r \x01(\tR\tlocalRole\x12\x1f\n" +
	"\vsecurity_id\x18\x0e \x01(\tR\n" +
	"securityId\x12'\n" +
	"\x0fsecurity_ticker\x18\x0f \x01(\tR\x0esecurityTicker\x12*\n" +
	"\x11seller_holding_id\x18\x10 \x01(\tR\x0fsellerHoldingId\x12\x1a\n" +
	"\bquantity\x18\x11 \x01(\x03R\bquantity\x12!\n" +
	"\fstrike_price\x18\x12 \x01(\tR\vstrikePrice\x12!\n" +
	"\fpremium_paid\x18\x13 \x01(\tR\vpremiumPaid\x12\x1a\n" +
	"\bcurrency\x18\x14 \x01(\tR\bcurrency\x12'\n" +
	"\x0fsettlement_date\x18\x15 \x01(\tR\x0esettlementDate\x12(\n" +
	"\x10accepted_by_side\x18\x16 \x01(\tR\x0eacceptedBySide\x12\x16\n" +
	"\x06status\x18\x17 \x01(\tR\x06status\x12\"\n" +
	"\rpremium_op_id\x18\x18 \x01(\tR\vpremiumOpId\x12$\n" +
	"\x0eexercise_op_id\x18\x19 \x01(\tR\fexerciseOpId\x12!\n" +
	"\fexercised_at\x18\x1a \x01(\tR\vexercisedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x1b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x1c \x01(\tR\tupdatedAt\"7\n" +
	"\x1dListExternalOTCThreadsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"V\n" +
	"\x1eListExternalOTCThreadsResponse\x124\n" +
	"\athreads\x18\x01 \x03(\v2\x1a.trading.ExternalOTCThreadR\athreads\":\n" +
	"\x1bGetExternalOTCThreadRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\"\xcb\x01\n" +
	"\x1cGetExternalOTCThreadResponse\x122\n" +
	"\x06thread\x18\x01 \x01(\v2\x1a.trading.ExternalOTCThreadR\x06thread\x12=\n" +
	"\n" +
	"iterations\x18\x02 \x03(\v2\x1d.trading.ExternalOTCIterationR\n" +
	"iterations\x128\n" +
	"\bcontract\x18\x03 \x01(\v2\x1c.trading.ExternalOTCContractR\bcontract\"\x90\x04\n" +
	"\x1dCreateExternalOTCOfferRequest\x12(\n" +
	"\x10remote_bank_code\x18\x01 \x01(\tR\x0eremoteBankCode\x12&\n" +
	"\x0fremote_user_ref\x18\x02 \x01(\tR\rremoteUserRef\x12.\n" +
	"\x13remote_display_name\x18\x03 \x01(\tR\x11remoteDisplayName\x12(\n" +
	"\x10buyer_account_id\x18\x04 \x01(\tR\x0ebuyerAccountId\x12*\n" +
	"\x11seller_holding_id\x18\x05 \x01(\tR\x0fsellerHoldingId\x12'\n" +
	"\x0fsecurity_ticker\x18\x06 \x01(\tR\x0esecurityTicker\x12#\n" +
	"\rsecurity_type\x18\a \x01(\tR\fsecurityType\x12\x1a\n" +
	"\bcurrency\x18\b \x01(\tR\bcurrency\x12\x1a\n" +
	"\bquantity\x18\t \x01(\x03R\bquantity\x12$\n" +
	"\x0eprice_per_unit\x18\n" +
	" \x01(\tR\fpricePerUnit\x12\x18\n" +
	"\apremium\x18\v \x01(\tR\apremium\x12'\n" +
	"\x0fsettlement_date\x18\f \x01(\tR\x0esettlementDate\x12(\n" +
	"\x10remote_thread_id\x18\r \x01(\tR\x0eremoteThreadId\"_\n" +
	"\x1eCreateExternalOTCOfferResponse\x12=\n" +
	"\flocal_mirror\x18\x01 \x01(\v2\x1a.trading.ExternalOTCThreadR\vlocalMirror\"\xd9\x01\n" +
	"\x18ExternalOTCActionRequest\x12\x1b\n" +
	"\tbank_code\x18\x01 \x01(\tR\bbankCode\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\x12$\n" +
	"\x0eprice_per_unit\x18\x04 \x01(\tR\fpricePerUnit\x12\x18\n" +
	"\apremium\x18\x05 \x01(\tR\apremium\x12'\n" +
	"\x0fsettlement_date\x18\x06 \x01(\tR\x0esettlementDate\"O\n" +
	"\x19ExternalOTCActionResponse\x122\n" +
	"\x06thread\x18\x01 \x01(\v2\x1a.trading.ExternalOTCThreadR\x06thread\"9\n" +
	"\x1fListExternalOTCContractsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"^\n" +
	" ListExternalOTCContractsResponse\x12:\n" +
	"\tcontracts\x18\x01 \x03(\v2\x1c.trading.ExternalOTCContractR\tcontracts\"\x88\x01\n" +
	"\"ExerciseExternalOTCContractRequest\x12\x1b\n" +
	"\tbank_code\x18\x01 \x01(\tR\bbankCode\x12\x1f\n" +
	"\vcontract_id\x18\x02 \x01(\tR\n" +
	"contractId\x12$\n" +
	"\x0eexercise_op_id\x18\x03 \x01(\tR\fexerciseOpId\"_\n" +
	"#ExerciseExternalOTCContractResponse\x128\n" +
	"\bcontract\x18\x01 \x01(\v2\x1c.trading.ExternalOTCContractR\bcontractB:Z8github.com/RAF-SI-2025/Banka-3-Backend/pkg/proto/tradingb\x06proto3"

var (
	file_trading_external_otc_proto_rawDescOnce sync.Once
	file_trading_external_otc_proto_rawDescData []byte
)

func file_trading_external_otc_proto_rawDescGZIP() []byte {
	file_trading_external_otc_proto_rawDescOnce.Do(func() {
		file_trading_external_otc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trading_external_otc_proto_rawDesc), len(file_trading_external_otc_proto_rawDesc)))
	})
	return file_trading_external_otc_proto_rawDescData
}

var file_trading_external_otc_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_trading_external_otc_proto_goTypes = []any{
	(*ExternalOTCThread)(nil),                   // 0: trading.ExternalOTCThread
	(*ExternalOTCIteration)(nil),                // 1: trading.ExternalOTCIteration
	(*ExternalOTCContract)(nil),                 // 2: trading.ExternalOTCContract
	(*ListExternalOTCThreadsRequest)(nil),       // 3: trading.ListExternalOTCThreadsRequest
	(*ListExternalOTCThreadsResponse)(nil),      // 4: trading.ListExternalOTCThreadsResponse
	(*GetExternalOTCThreadRequest)(nil),         // 5: trading.GetExternalOTCThreadRequest
	(*GetExternalOTCThreadResponse)(nil),        // 6: trading.GetExternalOTCThreadResponse
	(*CreateExternalOTCOfferRequest)(nil),       // 7: trading.CreateExternalOTCOfferRequest
	(*CreateExternalOTCOfferResponse)(nil),      // 8: trading.CreateExternalOTCOfferResponse
	(*ExternalOTCActionRequest)(nil),            // 9: trading.ExternalOTCActionRequest
	(*ExternalOTCActionResponse)(nil),           // 10: trading.ExternalOTCActionResponse
	(*ListExternalOTCContractsRequest)(nil),     // 11: trading.ListExternalOTCContractsRequest
	(*ListExternalOTCContractsResponse)(nil),    // 12: trading.ListExternalOTCContractsResponse
	(*ExerciseExternalOTCContractRequest)(nil),  // 13: trading.ExerciseExternalOTCContractRequest
	(*ExerciseExternalOTCContractResponse)(nil), // 14: trading.ExerciseExternalOTCContractResponse
}
var file_trading_external_otc_proto_depIdxs = []int32{
	0, // 0: trading.ListExternalOTCThreadsResponse.threads:type_name -> trading.ExternalOTCThread
	0, // 1: trading.GetExternalOTCThreadResponse.thread:type_name -> trading.ExternalOTCThread
	1, // 2: trading.GetExternalOTCThreadResponse.iterations:type_name -> trading.ExternalOTCIteration
	2, // 3: trading.GetExternalOTCThreadResponse.contract:type_name -> trading.ExternalOTCContract
	0, // 4: trading.CreateExternalOTCOfferResponse.local_mirror:type_name -> trading.ExternalOTCThread
	0, // 5: trading.ExternalOTCActionResponse.thread:type_name -> trading.ExternalOTCThread
	2, // 6: trading.ListExternalOTCContractsResponse.contracts:type_name -> trading.ExternalOTCContract
	2, // 7: trading.ExerciseExternalOTCContractResponse.contract:type_name -> trading.ExternalOTCContract
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_trading_external_otc_proto_init() }
func file_trading_external_otc_proto_init() {
	if File_trading_external_otc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trading_external_otc_proto_rawDesc), len(file_trading_external_otc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trading_external_otc_proto_goTypes,
		DependencyIndexes: file_trading_external_otc_proto_depIdxs,
		MessageInfos:      file_trading_external_otc_proto_msgTypes,
	}.Build()
	File_trading_external_otc_proto = out.File
	file_trading_external_otc_proto_goTypes = nil
	file_trading_external_otc_proto_depIdxs = nil
}
