// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: trading/trading.proto

package trading

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_trading_trading_proto protoreflect.FileDescriptor

const file_trading_trading_proto_rawDesc = "" +
	"\n" +
	"\x15trading/trading.proto\x12\atrading\x1a\x16trading/exchange.proto\x1a\x15trading/listing.proto\x1a\x13trading/forex.proto\x1a\x14trading/option.proto\x1a\x13trading/order.proto\x1a\x15trading/holding.proto\x1a\x11trading/tax.proto\x1a\x1atrading/external_otc.proto2\x9c\x14\n" +
	"\x0eTradingService\x12N\n" +
	"\rListExchanges\x12\x1d.trading.ListExchangesRequest\x1a\x1e.trading.ListExchangesResponse\x12l\n" +
	"\x17SetExchangeOpenOverride\x12'.trading.SetExchangeOpenOverrideRequest\x1a(.trading.SetExchangeOpenOverrideResponse\x12r\n" +
	"\x19SetExchangeClosedOverride\x12).trading.SetExchangeClosedOverrideRequest\x1a*.trading.SetExchangeClosedOverrideResponse\x12K\n" +
	"\fListListings\x12\x1c.trading.ListListingsRequest\x1a\x1d.trading.ListListingsResponse\x12E\n" +
	"\n" +
	"GetListing\x12\x1a.trading.GetListingRequest\x1a\x1b.trading.GetListingResponse\x12]\n" +
	"\x12ListListingHistory\x12\".trading.ListListingHistoryRequest\x1a#.trading.ListListingHistoryResponse\x12Q\n" +
	"\x0eListForexPairs\x12\x1e.trading.ListForexPairsRequest\x1a\x1f.trading.ListForexPairsResponse\x12T\n" +
	"\x0fListOptionDates\x12\x1f.trading.ListOptionDatesRequest\x1a .trading.ListOptionDatesResponse\x12H\n" +
	"\vListOptions\x12\x1b.trading.ListOptionsRequest\x1a\x1c.trading.ListOptionsResponse\x12Q\n" +
	"\x0eExerciseOption\x12\x1e.trading.ExerciseOptionRequest\x1a\x1f.trading.ExerciseOptionResponse\x12H\n" +
	"\vCreateOrder\x12\x1b.trading.CreateOrderRequest\x1a\x1c.trading.CreateOrderResponse\x12E\n" +
	"\n" +
	"ListOrders\x12\x1a.trading.ListOrdersRequest\x1a\x1b.trading.ListOrdersResponse\x12K\n" +
	"\fApproveOrder\x12\x1c.trading.ApproveOrderRequest\x1a\x1d.trading.ApproveOrderResponse\x12K\n" +
	"\fDeclineOrder\x12\x1c.trading.DeclineOrderRequest\x1a\x1d.trading.DeclineOrderResponse\x12H\n" +
	"\vCancelOrder\x12\x1b.trading.CancelOrderRequest\x1a\x1c.trading.CancelOrderResponse\x12K\n" +
	"\fListHoldings\x12\x1c.trading.ListHoldingsRequest\x1a\x1d.trading.ListHoldingsResponse\x12H\n" +
	"\vSellHolding\x12\x1b.trading.SellHoldingRequest\x1a\x1c.trading.SellHoldingResponse\x12W\n" +
	"\x10SetHoldingPublic\x12 .trading.SetHoldingPublicRequest\x1a!.trading.SetHoldingPublicResponse\x12i\n" +
	"\x16ListExternalOTCThreads\x12&.trading.ListExternalOTCThreadsRequest\x1a'.trading.ListExternalOTCThreadsResponse\x12c\n" +
	"\x14GetExternalOTCThread\x12$.trading.GetExternalOTCThreadRequest\x1a%.trading.GetExternalOTCThreadResponse\x12i\n" +
	"\x16CreateExternalOTCOffer\x12&.trading.CreateExternalOTCOfferRequest\x1a'.trading.CreateExternalOTCOfferResponse\x12`\n" +
	"\x17CounterExternalOTCOffer\x12!.trading.ExternalOTCActionRequest\x1a\".trading.ExternalOTCActionResponse\x12a\n" +
	"\x18WithdrawExternalOTCOffer\x12!.trading.ExternalOTCActionRequest\x1a\".trading.ExternalOTCActionResponse\x12_\n" +
	"\x16AcceptExternalOTCOffer\x12!.trading.ExternalOTCActionRequest\x1a\".trading.ExternalOTCActionResponse\x12o\n" +
	"\x18ListExternalOTCContracts\x12(.trading.ListExternalOTCContractsRequest\x1a).trading.ListExternalOTCContractsResponse\x12x\n" +
	"\x1bExerciseExternalOTCContract\x12+.trading.ExerciseExternalOTCContractRequest\x1a,.trading.ExerciseExternalOTCContractResponse\x12T\n" +
	"\x0fRunCapitalGains\x12\x1f.trading.RunCapitalGainsRequest\x1a .trading.RunCapitalGainsResponse\x12K\n" +
	"\fListTaxDebts\x12\x1c.trading.ListTaxDebtsRequest\x1a\x1d.trading.ListTaxDebtsResponse\x12K\n" +
	"\fGetMyTaxInfo\x12\x1c.trading.GetMyTaxInfoRequest\x1a\x1d.trading.GetMyTaxInfoResponseB:Z8github.com/RAF-SI-2025/Banka-3-Backend/pkg/proto/tradingb\x06proto3"

var file_trading_trading_proto_goTypes = []any{
	(*ListExchangesRequest)(nil),                // 0: trading.ListExchangesRequest
	(*SetExchangeOpenOverrideRequest)(nil),      // 1: trading.SetExchangeOpenOverrideRequest
	(*SetExchangeClosedOverrideRequest)(nil),    // 2: trading.SetExchangeClosedOverrideRequest
	(*ListListingsRequest)(nil),                 // 3: trading.ListListingsRequest
	(*GetListingRequest)(nil),                   // 4: trading.GetListingRequest
	(*ListListingHistoryRequest)(nil),           // 5: trading.ListListingHistoryRequest
	(*ListForexPairsRequest)(nil),               // 6: trading.ListForexPairsRequest
	(*ListOptionDatesRequest)(nil),              // 7: trading.ListOptionDatesRequest
	(*ListOptionsRequest)(nil),                  // 8: trading.ListOptionsRequest
	(*ExerciseOptionRequest)(nil),               // 9: trading.ExerciseOptionRequest
	(*CreateOrderRequest)(nil),                  // 10: trading.CreateOrderRequest
	(*ListOrdersRequest)(nil),                   // 11: trading.ListOrdersRequest
	(*ApproveOrderRequest)(nil),                 // 12: trading.ApproveOrderRequest
	(*DeclineOrderRequest)(nil),                 // 13: trading.DeclineOrderRequest
	(*CancelOrderRequest)(nil),                  // 14: trading.CancelOrderRequest
	(*ListHoldingsRequest)(nil),                 // 15: trading.ListHoldingsRequest
	(*SellHoldingRequest)(nil),                  // 16: trading.SellHoldingRequest
	(*SetHoldingPublicRequest)(nil),             // 17: trading.SetHoldingPublicRequest
	(*ListExternalOTCThreadsRequest)(nil),       // 18: trading.ListExternalOTCThreadsRequest
	(*GetExternalOTCThreadRequest)(nil),         // 19: trading.GetExternalOTCThreadRequest
	(*CreateExternalOTCOfferRequest)(nil),       // 20: trading.CreateExternalOTCOfferRequest
	(*ExternalOTCActionRequest)(nil),            // 21: trading.ExternalOTCActionRequest
	(*ListExternalOTCContractsRequest)(nil),     // 22: trading.ListExternalOTCContractsRequest
	(*ExerciseExternalOTCContractRequest)(nil),  // 23: trading.ExerciseExternalOTCContractRequest
	(*RunCapitalGainsRequest)(nil),              // 24: trading.RunCapitalGainsRequest
	(*ListTaxDebtsRequest)(nil),                 // 25: trading.ListTaxDebtsRequest
	(*GetMyTaxInfoRequest)(nil),                 // 26: trading.GetMyTaxInfoRequest
	(*ListExchangesResponse)(nil),               // 27: trading.ListExchangesResponse
	(*SetExchangeOpenOverrideResponse)(nil),     // 28: trading.SetExchangeOpenOverrideResponse
	(*SetExchangeClosedOverrideResponse)(nil),   // 29: trading.SetExchangeClosedOverrideResponse
	(*ListListingsResponse)(nil),                // 30: trading.ListListingsResponse
	(*GetListingResponse)(nil),                  // 31: trading.GetListingResponse
	(*ListListingHistoryResponse)(nil),          // 32: trading.ListListingHistoryResponse
	(*ListForexPairsResponse)(nil),              // 33: trading.ListForexPairsResponse
	(*ListOptionDatesResponse)(nil),             // 34: trading.ListOptionDatesResponse
	(*ListOptionsResponse)(nil),                 // 35: trading.ListOptionsResponse
	(*ExerciseOptionResponse)(nil),              // 36: trading.ExerciseOptionResponse
	(*CreateOrderResponse)(nil),                 // 37: trading.CreateOrderResponse
	(*ListOrdersResponse)(nil),                  // 38: trading.ListOrdersResponse
	(*ApproveOrderResponse)(nil),                // 39: trading.ApproveOrderResponse
	(*DeclineOrderResponse)(nil),                // 40: trading.DeclineOrderResponse
	(*CancelOrderResponse)(nil),                 // 41: trading.CancelOrderResponse
	(*ListHoldingsResponse)(nil),                // 42: trading.ListHoldingsResponse
	(*SellHoldingResponse)(nil),                 // 43: trading.SellHoldingResponse
	(*SetHoldingPublicResponse)(nil),            // 44: trading.SetHoldingPublicResponse
	(*ListExternalOTCThreadsResponse)(nil),      // 45: trading.ListExternalOTCThreadsResponse
	(*GetExternalOTCThreadResponse)(nil),        // 46: trading.GetExternalOTCThreadResponse
	(*CreateExternalOTCOfferResponse)(nil),      // 47: trading.CreateExternalOTCOfferResponse
	(*ExternalOTCActionResponse)(nil),           // 48: trading.ExternalOTCActionResponse
	(*ListExternalOTCContractsResponse)(nil),    // 49: trading.ListExternalOTCContractsResponse
	(*ExerciseExternalOTCContractResponse)(nil), // 50: trading.ExerciseExternalOTCContractResponse
	(*RunCapitalGainsResponse)(nil),             // 51: trading.RunCapitalGainsResponse
	(*ListTaxDebtsResponse)(nil),                // 52: trading.ListTaxDebtsResponse
	(*GetMyTaxInfoResponse)(nil),                // 53: trading.GetMyTaxInfoResponse
}
var file_trading_trading_proto_depIdxs = []int32{
	0,  // 0: trading.TradingService.ListExchanges:input_type -> trading.ListExchangesRequest
	1,  // 1: trading.TradingService.SetExchangeOpenOverride:input_type -> trading.SetExchangeOpenOverrideRequest
	2,  // 2: trading.TradingService.SetExchangeClosedOverride:input_type -> trading.SetExchangeClosedOverrideRequest
	3,  // 3: trading.TradingService.ListListings:input_type -> trading.ListListingsRequest
	4,  // 4: trading.TradingService.GetListing:input_type -> trading.GetListingRequest
	5,  // 5: trading.TradingService.ListListingHistory:input_type -> trading.ListListingHistoryRequest
	6,  // 6: trading.TradingService.ListForexPairs:input_type -> trading.ListForexPairsRequest
	7,  // 7: trading.TradingService.ListOptionDates:input_type -> trading.ListOptionDatesRequest
	8,  // 8: trading.TradingService.ListOptions:input_type -> trading.ListOptionsRequest
	9,  // 9: trading.TradingService.ExerciseOption:input_type -> trading.ExerciseOptionRequest
	10, // 10: trading.TradingService.CreateOrder:input_type -> trading.CreateOrderRequest
	11, // 11: trading.TradingService.ListOrders:input_type -> trading.ListOrdersRequest
	12, // 12: trading.TradingService.ApproveOrder:input_type -> trading.ApproveOrderRequest
	13, // 13: trading.TradingService.DeclineOrder:input_type -> trading.DeclineOrderRequest
	14, // 14: trading.TradingService.CancelOrder:input_type -> trading.CancelOrderRequest
	15, // 15: trading.TradingService.ListHoldings:input_type -> trading.ListHoldingsRequest
	16, // 16: trading.TradingService.SellHolding:input_type -> trading.SellHoldingRequest
	17, // 17: trading.TradingService.SetHoldingPublic:input_type -> trading.SetHoldingPublicRequest
	18, // 18: trading.TradingService.ListExternalOTCThreads:input_type -> trading.ListExternalOTCThreadsRequest
	19, // 19: trading.TradingService.GetExternalOTCThread:input_type -> trading.GetExternalOTCThreadRequest
	20, // 20: trading.TradingService.CreateExternalOTCOffer:input_type -> trading.CreateExternalOTCOfferRequest
	21, // 21: trading.TradingService.CounterExternalOTCOffer:input_type -> trading.ExternalOTCActionRequest
	21, // 22: trading.TradingService.WithdrawExternalOTCOffer:input_type -> trading.ExternalOTCActionRequest
	21, // 23: trading.TradingService.AcceptExternalOTCOffer:input_type -> trading.ExternalOTCActionRequest
	22, // 24: trading.TradingService.ListExternalOTCContracts:input_type -> trading.ListExternalOTCContractsRequest
	23, // 25: trading.TradingService.ExerciseExternalOTCContract:input_type -> trading.ExerciseExternalOTCContractRequest
	24, // 26: trading.TradingService.RunCapitalGains:input_type -> trading.RunCapitalGainsRequest
	25, // 27: trading.TradingService.ListTaxDebts:input_type -> trading.ListTaxDebtsRequest
	26, // 28: trading.TradingService.GetMyTaxInfo:input_type -> trading.GetMyTaxInfoRequest
	27, // 29: trading.TradingService.ListExchanges:output_type -> trading.ListExchangesResponse
	28, // 30: trading.TradingService.SetExchangeOpenOverride:output_type -> trading.SetExchangeOpenOverrideResponse
	29, // 31: trading.TradingService.SetExchangeClosedOverride:output_type -> trading.SetExchangeClosedOverrideResponse
	30, // 32: trading.TradingService.ListListings:output_type -> trading.ListListingsResponse
	31, // 33: trading.TradingService.GetListing:output_type -> trading.GetListingResponse
	32, // 34: trading.TradingService.ListListingHistory:output_type -> trading.ListListingHistoryResponse
	33, // 35: trading.TradingService.ListForexPairs:output_type -> trading.ListForexPairsResponse
	34, // 36: trading.TradingService.ListOptionDates:output_type -> trading.ListOptionDatesResponse
	35, // 37: trading.TradingService.ListOptions:output_type -> trading.ListOptionsResponse
	36, // 38: trading.TradingService.ExerciseOption:output_type -> trading.ExerciseOptionResponse
	37, // 39: trading.TradingService.CreateOrder:output_type -> trading.CreateOrderResponse
	38, // 40: trading.TradingService.ListOrders:output_type -> trading.ListOrdersResponse
	39, // 41: trading.TradingService.ApproveOrder:output_type -> trading.ApproveOrderResponse
	40, // 42: trading.TradingService.DeclineOrder:output_type -> trading.DeclineOrderResponse
	41, // 43: trading.TradingService.CancelOrder:output_type -> trading.CancelOrderResponse
	42, // 44: trading.TradingService.ListHoldings:output_type -> trading.ListHoldingsResponse
	43, // 45: trading.TradingService.SellHolding:output_type -> trading.SellHoldingResponse
	44, // 46: trading.TradingService.SetHoldingPublic:output_type -> trading.SetHoldingPublicResponse
	45, // 47: trading.TradingService.ListExternalOTCThreads:output_type -> trading.ListExternalOTCThreadsResponse
	46, // 48: trading.TradingService.GetExternalOTCThread:output_type -> trading.GetExternalOTCThreadResponse
	47, // 49: trading.TradingService.CreateExternalOTCOffer:output_type -> trading.CreateExternalOTCOfferResponse
	48, // 50: trading.TradingService.CounterExternalOTCOffer:output_type -> trading.ExternalOTCActionResponse
	48, // 51: trading.TradingService.WithdrawExternalOTCOffer:output_type -> trading.ExternalOTCActionResponse
	48, // 52: trading.TradingService.AcceptExternalOTCOffer:output_type -> trading.ExternalOTCActionResponse
	49, // 53: trading.TradingService.ListExternalOTCContracts:output_type -> trading.ListExternalOTCContractsResponse
	50, // 54: trading.TradingService.ExerciseExternalOTCContract:output_type -> trading.ExerciseExternalOTCContractResponse
	51, // 55: trading.TradingService.RunCapitalGains:output_type -> trading.RunCapitalGainsResponse
	52, // 56: trading.TradingService.ListTaxDebts:output_type -> trading.ListTaxDebtsResponse
	53, // 57: trading.TradingService.GetMyTaxInfo:output_type -> trading.GetMyTaxInfoResponse
	29, // [29:58] is the sub-list for method output_type
	0,  // [0:29] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_trading_trading_proto_init() }
func file_trading_trading_proto_init() {
	if File_trading_trading_proto != nil {
		return
	}
	file_trading_exchange_proto_init()
	file_trading_listing_proto_init()
	file_trading_forex_proto_init()
	file_trading_option_proto_init()
	file_trading_order_proto_init()
	file_trading_holding_proto_init()
	file_trading_tax_proto_init()
	file_trading_external_otc_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trading_trading_proto_rawDesc), len(file_trading_trading_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trading_trading_proto_goTypes,
		DependencyIndexes: file_trading_trading_proto_depIdxs,
	}.Build()
	File_trading_trading_proto = out.File
	file_trading_trading_proto_goTypes = nil
	file_trading_trading_proto_depIdxs = nil
}
