// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: trading/trading.proto

package trading

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_trading_trading_proto protoreflect.FileDescriptor

const file_trading_trading_proto_rawDesc = "" +
	"\n" +
	"\x15trading/trading.proto\x12\atrading\x1a\x16trading/exchange.proto\x1a\x15trading/listing.proto\x1a\x13trading/forex.proto\x1a\x14trading/option.proto\x1a\x13trading/order.proto\x1a\x15trading/holding.proto\x1a\x11trading/tax.proto2\xd0\r\n" +
	"\x0eTradingService\x12N\n" +
	"\rListExchanges\x12\x1d.trading.ListExchangesRequest\x1a\x1e.trading.ListExchangesResponse\x12l\n" +
	"\x17SetExchangeOpenOverride\x12'.trading.SetExchangeOpenOverrideRequest\x1a(.trading.SetExchangeOpenOverrideResponse\x12r\n" +
	"\x19SetExchangeClosedOverride\x12).trading.SetExchangeClosedOverrideRequest\x1a*.trading.SetExchangeClosedOverrideResponse\x12K\n" +
	"\fListListings\x12\x1c.trading.ListListingsRequest\x1a\x1d.trading.ListListingsResponse\x12E\n" +
	"\n" +
	"GetListing\x12\x1a.trading.GetListingRequest\x1a\x1b.trading.GetListingResponse\x12]\n" +
	"\x12ListListingHistory\x12\".trading.ListListingHistoryRequest\x1a#.trading.ListListingHistoryResponse\x12Q\n" +
	"\x0eListForexPairs\x12\x1e.trading.ListForexPairsRequest\x1a\x1f.trading.ListForexPairsResponse\x12T\n" +
	"\x0fListOptionDates\x12\x1f.trading.ListOptionDatesRequest\x1a .trading.ListOptionDatesResponse\x12H\n" +
	"\vListOptions\x12\x1b.trading.ListOptionsRequest\x1a\x1c.trading.ListOptionsResponse\x12Q\n" +
	"\x0eExerciseOption\x12\x1e.trading.ExerciseOptionRequest\x1a\x1f.trading.ExerciseOptionResponse\x12H\n" +
	"\vCreateOrder\x12\x1b.trading.CreateOrderRequest\x1a\x1c.trading.CreateOrderResponse\x12E\n" +
	"\n" +
	"ListOrders\x12\x1a.trading.ListOrdersRequest\x1a\x1b.trading.ListOrdersResponse\x12K\n" +
	"\fApproveOrder\x12\x1c.trading.ApproveOrderRequest\x1a\x1d.trading.ApproveOrderResponse\x12K\n" +
	"\fDeclineOrder\x12\x1c.trading.DeclineOrderRequest\x1a\x1d.trading.DeclineOrderResponse\x12H\n" +
	"\vCancelOrder\x12\x1b.trading.CancelOrderRequest\x1a\x1c.trading.CancelOrderResponse\x12K\n" +
	"\fListHoldings\x12\x1c.trading.ListHoldingsRequest\x1a\x1d.trading.ListHoldingsResponse\x12H\n" +
	"\vSellHolding\x12\x1b.trading.SellHoldingRequest\x1a\x1c.trading.SellHoldingResponse\x12W\n" +
	"\x10SetHoldingPublic\x12 .trading.SetHoldingPublicRequest\x1a!.trading.SetHoldingPublicResponse\x12T\n" +
	"\x0fRunCapitalGains\x12\x1f.trading.RunCapitalGainsRequest\x1a .trading.RunCapitalGainsResponse\x12K\n" +
	"\fListTaxDebts\x12\x1c.trading.ListTaxDebtsRequest\x1a\x1d.trading.ListTaxDebtsResponse\x12K\n" +
	"\fGetMyTaxInfo\x12\x1c.trading.GetMyTaxInfoRequest\x1a\x1d.trading.GetMyTaxInfoResponseB:Z8github.com/RAF-SI-2025/Banka-3-Backend/pkg/proto/tradingb\x06proto3"

var file_trading_trading_proto_goTypes = []any{
	(*ListExchangesRequest)(nil),              // 0: trading.ListExchangesRequest
	(*SetExchangeOpenOverrideRequest)(nil),    // 1: trading.SetExchangeOpenOverrideRequest
	(*SetExchangeClosedOverrideRequest)(nil),  // 2: trading.SetExchangeClosedOverrideRequest
	(*ListListingsRequest)(nil),               // 3: trading.ListListingsRequest
	(*GetListingRequest)(nil),                 // 4: trading.GetListingRequest
	(*ListListingHistoryRequest)(nil),         // 5: trading.ListListingHistoryRequest
	(*ListForexPairsRequest)(nil),             // 6: trading.ListForexPairsRequest
	(*ListOptionDatesRequest)(nil),            // 7: trading.ListOptionDatesRequest
	(*ListOptionsRequest)(nil),                // 8: trading.ListOptionsRequest
	(*ExerciseOptionRequest)(nil),             // 9: trading.ExerciseOptionRequest
	(*CreateOrderRequest)(nil),                // 10: trading.CreateOrderRequest
	(*ListOrdersRequest)(nil),                 // 11: trading.ListOrdersRequest
	(*ApproveOrderRequest)(nil),               // 12: trading.ApproveOrderRequest
	(*DeclineOrderRequest)(nil),               // 13: trading.DeclineOrderRequest
	(*CancelOrderRequest)(nil),                // 14: trading.CancelOrderRequest
	(*ListHoldingsRequest)(nil),               // 15: trading.ListHoldingsRequest
	(*SellHoldingRequest)(nil),                // 16: trading.SellHoldingRequest
	(*SetHoldingPublicRequest)(nil),           // 17: trading.SetHoldingPublicRequest
	(*RunCapitalGainsRequest)(nil),            // 18: trading.RunCapitalGainsRequest
	(*ListTaxDebtsRequest)(nil),               // 19: trading.ListTaxDebtsRequest
	(*GetMyTaxInfoRequest)(nil),               // 20: trading.GetMyTaxInfoRequest
	(*ListExchangesResponse)(nil),             // 21: trading.ListExchangesResponse
	(*SetExchangeOpenOverrideResponse)(nil),   // 22: trading.SetExchangeOpenOverrideResponse
	(*SetExchangeClosedOverrideResponse)(nil), // 23: trading.SetExchangeClosedOverrideResponse
	(*ListListingsResponse)(nil),              // 24: trading.ListListingsResponse
	(*GetListingResponse)(nil),                // 25: trading.GetListingResponse
	(*ListListingHistoryResponse)(nil),        // 26: trading.ListListingHistoryResponse
	(*ListForexPairsResponse)(nil),            // 27: trading.ListForexPairsResponse
	(*ListOptionDatesResponse)(nil),           // 28: trading.ListOptionDatesResponse
	(*ListOptionsResponse)(nil),               // 29: trading.ListOptionsResponse
	(*ExerciseOptionResponse)(nil),            // 30: trading.ExerciseOptionResponse
	(*CreateOrderResponse)(nil),               // 31: trading.CreateOrderResponse
	(*ListOrdersResponse)(nil),                // 32: trading.ListOrdersResponse
	(*ApproveOrderResponse)(nil),              // 33: trading.ApproveOrderResponse
	(*DeclineOrderResponse)(nil),              // 34: trading.DeclineOrderResponse
	(*CancelOrderResponse)(nil),               // 35: trading.CancelOrderResponse
	(*ListHoldingsResponse)(nil),              // 36: trading.ListHoldingsResponse
	(*SellHoldingResponse)(nil),               // 37: trading.SellHoldingResponse
	(*SetHoldingPublicResponse)(nil),          // 38: trading.SetHoldingPublicResponse
	(*RunCapitalGainsResponse)(nil),           // 39: trading.RunCapitalGainsResponse
	(*ListTaxDebtsResponse)(nil),              // 40: trading.ListTaxDebtsResponse
	(*GetMyTaxInfoResponse)(nil),              // 41: trading.GetMyTaxInfoResponse
}
var file_trading_trading_proto_depIdxs = []int32{
	0,  // 0: trading.TradingService.ListExchanges:input_type -> trading.ListExchangesRequest
	1,  // 1: trading.TradingService.SetExchangeOpenOverride:input_type -> trading.SetExchangeOpenOverrideRequest
	2,  // 2: trading.TradingService.SetExchangeClosedOverride:input_type -> trading.SetExchangeClosedOverrideRequest
	3,  // 3: trading.TradingService.ListListings:input_type -> trading.ListListingsRequest
	4,  // 4: trading.TradingService.GetListing:input_type -> trading.GetListingRequest
	5,  // 5: trading.TradingService.ListListingHistory:input_type -> trading.ListListingHistoryRequest
	6,  // 6: trading.TradingService.ListForexPairs:input_type -> trading.ListForexPairsRequest
	7,  // 7: trading.TradingService.ListOptionDates:input_type -> trading.ListOptionDatesRequest
	8,  // 8: trading.TradingService.ListOptions:input_type -> trading.ListOptionsRequest
	9,  // 9: trading.TradingService.ExerciseOption:input_type -> trading.ExerciseOptionRequest
	10, // 10: trading.TradingService.CreateOrder:input_type -> trading.CreateOrderRequest
	11, // 11: trading.TradingService.ListOrders:input_type -> trading.ListOrdersRequest
	12, // 12: trading.TradingService.ApproveOrder:input_type -> trading.ApproveOrderRequest
	13, // 13: trading.TradingService.DeclineOrder:input_type -> trading.DeclineOrderRequest
	14, // 14: trading.TradingService.CancelOrder:input_type -> trading.CancelOrderRequest
	15, // 15: trading.TradingService.ListHoldings:input_type -> trading.ListHoldingsRequest
	16, // 16: trading.TradingService.SellHolding:input_type -> trading.SellHoldingRequest
	17, // 17: trading.TradingService.SetHoldingPublic:input_type -> trading.SetHoldingPublicRequest
	18, // 18: trading.TradingService.RunCapitalGains:input_type -> trading.RunCapitalGainsRequest
	19, // 19: trading.TradingService.ListTaxDebts:input_type -> trading.ListTaxDebtsRequest
	20, // 20: trading.TradingService.GetMyTaxInfo:input_type -> trading.GetMyTaxInfoRequest
	21, // 21: trading.TradingService.ListExchanges:output_type -> trading.ListExchangesResponse
	22, // 22: trading.TradingService.SetExchangeOpenOverride:output_type -> trading.SetExchangeOpenOverrideResponse
	23, // 23: trading.TradingService.SetExchangeClosedOverride:output_type -> trading.SetExchangeClosedOverrideResponse
	24, // 24: trading.TradingService.ListListings:output_type -> trading.ListListingsResponse
	25, // 25: trading.TradingService.GetListing:output_type -> trading.GetListingResponse
	26, // 26: trading.TradingService.ListListingHistory:output_type -> trading.ListListingHistoryResponse
	27, // 27: trading.TradingService.ListForexPairs:output_type -> trading.ListForexPairsResponse
	28, // 28: trading.TradingService.ListOptionDates:output_type -> trading.ListOptionDatesResponse
	29, // 29: trading.TradingService.ListOptions:output_type -> trading.ListOptionsResponse
	30, // 30: trading.TradingService.ExerciseOption:output_type -> trading.ExerciseOptionResponse
	31, // 31: trading.TradingService.CreateOrder:output_type -> trading.CreateOrderResponse
	32, // 32: trading.TradingService.ListOrders:output_type -> trading.ListOrdersResponse
	33, // 33: trading.TradingService.ApproveOrder:output_type -> trading.ApproveOrderResponse
	34, // 34: trading.TradingService.DeclineOrder:output_type -> trading.DeclineOrderResponse
	35, // 35: trading.TradingService.CancelOrder:output_type -> trading.CancelOrderResponse
	36, // 36: trading.TradingService.ListHoldings:output_type -> trading.ListHoldingsResponse
	37, // 37: trading.TradingService.SellHolding:output_type -> trading.SellHoldingResponse
	38, // 38: trading.TradingService.SetHoldingPublic:output_type -> trading.SetHoldingPublicResponse
	39, // 39: trading.TradingService.RunCapitalGains:output_type -> trading.RunCapitalGainsResponse
	40, // 40: trading.TradingService.ListTaxDebts:output_type -> trading.ListTaxDebtsResponse
	41, // 41: trading.TradingService.GetMyTaxInfo:output_type -> trading.GetMyTaxInfoResponse
	21, // [21:42] is the sub-list for method output_type
	0,  // [0:21] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_trading_trading_proto_init() }
func file_trading_trading_proto_init() {
	if File_trading_trading_proto != nil {
		return
	}
	file_trading_exchange_proto_init()
	file_trading_listing_proto_init()
	file_trading_forex_proto_init()
	file_trading_option_proto_init()
	file_trading_order_proto_init()
	file_trading_holding_proto_init()
	file_trading_tax_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trading_trading_proto_rawDesc), len(file_trading_trading_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trading_trading_proto_goTypes,
		DependencyIndexes: file_trading_trading_proto_depIdxs,
	}.Build()
	File_trading_trading_proto = out.File
	file_trading_trading_proto_goTypes = nil
	file_trading_trading_proto_depIdxs = nil
}
