apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: banka-analytics
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - driver-rbac.yaml
  - db-secret.template.yaml
  - scheduled-sparkapplication.yaml
