apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: banka-platform
resources:
  - namespace.yaml
  - gateway-configmap.yaml
  - gateway-deployment.yaml
  - gateway-service.yaml
  - gateway-hpa.yaml
  - gateway-pdb.yaml
